"""Multi-protocol client model code generator for TypeScript and Python Pydantic v2."""

from __future__ import annotations

import json
import re
from enum import Enum
from typing import Any

from contracthub.core.comparator import SchemaComparator
from contracthub.core.models import (
    GraphQLAST,
    JsonSchemaAST,
    OpenApiAST,
    ProtoAST,
    ProtoFieldAST,
    ProtoMessageAST,
    SchemaType,
)
from contracthub.parsers.avro_parser import AvroParser, AvroRecordAST
from contracthub.parsers.graphql_parser import GraphQLParser
from contracthub.parsers.json_schema_parser import JsonSchemaParser
from contracthub.parsers.openapi_parser import OpenApiParser
from contracthub.parsers.proto_parser import ProtoParser


class TargetLanguage(str, Enum):
    TYPESCRIPT = "typescript"
    PYDANTIC = "pydantic"


class CodeGenerator:
    """Generates typed client data models from schemas."""

    @classmethod
    def generate(
        cls,
        schema_content: str,
        target: str | TargetLanguage,
        schema_type: SchemaType | None = None,
    ) -> str:
        lang = cls._normalize_target(target)
        detected_type = schema_type or SchemaComparator.detect_schema_type(schema_content)

        if detected_type == SchemaType.PROTOBUF:
            ast = ProtoParser.parse_string(schema_content)
            return cls._generate_proto(ast, lang)
        elif detected_type == SchemaType.AVRO:
            ast = AvroParser.parse_string(schema_content)
            return cls._generate_avro(ast, lang)
        elif detected_type == SchemaType.JSON_SCHEMA:
            ast = JsonSchemaParser.parse_string(schema_content)
            return cls._generate_json_schema(ast, lang)
        elif detected_type == SchemaType.OPENAPI:
            ast = OpenApiParser.parse_string(schema_content)
            return cls._generate_openapi(ast, lang)
        elif detected_type == SchemaType.GRAPHQL:
            ast_gql = GraphQLParser.parse_string(schema_content)
            return cls._generate_graphql(ast_gql, lang)
        else:
            raise ValueError(f"Unsupported schema type: {detected_type}")

    @classmethod
    def _normalize_target(cls, target: str | TargetLanguage) -> TargetLanguage:
        if isinstance(target, TargetLanguage):
            return target
        val = str(target).strip().lower()
        if val in ("typescript", "ts"):
            return TargetLanguage.TYPESCRIPT
        elif val in ("pydantic", "python", "py"):
            return TargetLanguage.PYDANTIC
        raise ValueError(
            f"Unsupported target language '{target}'. Choose from 'typescript' or 'pydantic'."
        )

    # -------------------------------------------------------------------------
    # PROTOBUF CODEGEN
    # -------------------------------------------------------------------------
    @classmethod
    def _generate_proto(cls, ast: ProtoAST, lang: TargetLanguage) -> str:
        if lang == TargetLanguage.TYPESCRIPT:
            lines = [
                "/**",
                " * Generated by ContractHub",
                f" * Syntax: {ast.syntax}",
                f" * Package: {ast.package or 'default'}",
                " */",
                "",
            ]

            # Enums
            for enum_name, enum_ast in ast.enums.items():
                lines.append(f"export enum {enum_name} {{")
                for val_name, val_num in enum_ast.values.items():
                    lines.append(f"  {val_name} = {val_num},")
                lines.append("}\n")

            # Messages
            for msg_ast in ast.messages.values():
                lines.extend(cls._proto_message_to_ts(msg_ast))

            return "\n".join(lines).strip() + "\n"

        else:  # PYDANTIC
            lines = [
                "# Generated by ContractHub",
                "from __future__ import annotations",
                "",
                "from enum import IntEnum",
                "from typing import Any",
                "from pydantic import BaseModel, Field",
                "",
            ]

            # Enums
            for enum_name, enum_ast in ast.enums.items():
                lines.append(f"class {enum_name}(IntEnum):")
                if not enum_ast.values:
                    lines.append("    pass\n")
                else:
                    for val_name, val_num in enum_ast.values.items():
                        lines.append(f"    {val_name} = {val_num}")
                    lines.append("")

            # Messages
            for msg_ast in ast.messages.values():
                lines.extend(cls._proto_message_to_pydantic(msg_ast))

            return "\n".join(lines).strip() + "\n"

    @classmethod
    def _proto_message_to_ts(cls, msg: ProtoMessageAST) -> list[str]:
        lines = []
        # Nested enums
        for nested_enum_name, nested_enum in msg.nested_enums.items():
            lines.append(f"export enum {msg.name}_{nested_enum_name} {{")
            for val_name, val_num in nested_enum.values.items():
                lines.append(f"  {val_name} = {val_num},")
            lines.append("}\n")

        # Nested messages
        for nested_msg in msg.nested_messages.values():
            lines.extend(cls._proto_message_to_ts(nested_msg))

        lines.append(f"export interface {msg.name} {{")
        for f_name, f in msg.fields.items():
            ts_type = cls._proto_type_to_ts(f)
            opt = "?" if f.cardinality == "optional" else ""
            lines.append(f"  {f_name}{opt}: {ts_type};")
        lines.append("}\n")
        return lines

    @classmethod
    def _proto_type_to_ts(cls, f: ProtoFieldAST) -> str:
        base_type = f.type
        mapping = {
            "string": "string",
            "bool": "boolean",
            "bytes": "string",
            "int32": "number",
            "int64": "number",
            "uint32": "number",
            "uint64": "number",
            "sint32": "number",
            "sint64": "number",
            "fixed32": "number",
            "fixed64": "number",
            "float": "number",
            "double": "number",
        }

        if base_type.startswith("map<"):
            map_match = re.match(r"map<([^,]+),\s*([^>]+)>", base_type)
            if map_match:
                k_ts = mapping.get(map_match.group(1).strip(), "string")
                v_ts = mapping.get(map_match.group(2).strip(), map_match.group(2).strip())
                return f"Record<{k_ts}, {v_ts}>"
            return "Record<string, any>"

        ts_mapped = mapping.get(base_type, base_type)
        if f.cardinality == "repeated":
            return f"{ts_mapped}[]"
        return ts_mapped

    @classmethod
    def _proto_message_to_pydantic(cls, msg: ProtoMessageAST) -> list[str]:
        lines = []
        # Nested enums
        for nested_enum_name, nested_enum in msg.nested_enums.items():
            lines.append(f"class {msg.name}_{nested_enum_name}(IntEnum):")
            for val_name, val_num in nested_enum.values.items():
                lines.append(f"    {val_name} = {val_num}")
            lines.append("")

        # Nested messages
        for nested_msg in msg.nested_messages.values():
            lines.extend(cls._proto_message_to_pydantic(nested_msg))

        lines.append(f"class {msg.name}(BaseModel):")
        if not msg.fields:
            lines.append("    pass\n")
            return lines

        for f_name, f in msg.fields.items():
            py_type, default_val = cls._proto_type_to_pydantic(f)
            if default_val:
                lines.append(f"    {f_name}: {py_type} = {default_val}")
            else:
                lines.append(f"    {f_name}: {py_type}")
        lines.append("")
        return lines

    @classmethod
    def _proto_type_to_pydantic(cls, f: ProtoFieldAST) -> tuple[str, str | None]:
        base_type = f.type
        mapping = {
            "string": "str",
            "bool": "bool",
            "bytes": "bytes",
            "int32": "int",
            "int64": "int",
            "uint32": "int",
            "uint64": "int",
            "sint32": "int",
            "sint64": "int",
            "fixed32": "int",
            "fixed64": "int",
            "float": "float",
            "double": "float",
        }

        if base_type.startswith("map<"):
            map_match = re.match(r"map<([^,]+),\s*([^>]+)>", base_type)
            if map_match:
                k_py = mapping.get(map_match.group(1).strip(), "str")
                v_py = mapping.get(map_match.group(2).strip(), map_match.group(2).strip())
                return f"dict[{k_py}, {v_py}]", "Field(default_factory=dict)"
            return "dict[str, Any]", "Field(default_factory=dict)"

        py_mapped = mapping.get(base_type, base_type)
        if f.cardinality == "repeated":
            return f"list[{py_mapped}]", "Field(default_factory=list)"
        elif f.cardinality == "optional":
            return f"{py_mapped} | None", "None"
        return py_mapped, None

    # -------------------------------------------------------------------------
    # AVRO CODEGEN
    # -------------------------------------------------------------------------
    @classmethod
    def _generate_avro(cls, ast: AvroRecordAST, lang: TargetLanguage) -> str:
        record_name = ast.name or "AvroRecord"

        if lang == TargetLanguage.TYPESCRIPT:
            lines = [
                "/**",
                " * Generated by ContractHub",
                f" * Record: {record_name}",
                f" * Namespace: {ast.namespace or 'default'}",
                " */",
                "",
                f"export interface {record_name} {{",
            ]

            for f_name, f in ast.fields.items():
                ts_type, is_opt = cls._avro_type_to_ts(f.type)
                opt = "?" if (is_opt or f.has_default) else ""
                lines.append(f"  {f_name}{opt}: {ts_type};")

            lines.append("}\n")
            return "\n".join(lines)

        else:  # PYDANTIC
            lines = [
                "# Generated by ContractHub",
                "from __future__ import annotations",
                "",
                "from typing import Any",
                "from pydantic import BaseModel, Field",
                "",
                f"class {record_name}(BaseModel):",
            ]

            if not ast.fields:
                lines.append("    pass\n")
                return "\n".join(lines)

            for f_name, f in ast.fields.items():
                py_type, default_repr = cls._avro_type_to_pydantic(f.type, f.has_default, f.default)
                if default_repr is not None:
                    lines.append(f"    {f_name}: {py_type} = {default_repr}")
                else:
                    lines.append(f"    {f_name}: {py_type}")

            lines.append("")
            return "\n".join(lines)

    @classmethod
    def _avro_type_to_ts(cls, avro_type: Any) -> tuple[str, bool]:
        mapping = {
            "string": "string",
            "boolean": "boolean",
            "bytes": "string",
            "int": "number",
            "long": "number",
            "float": "number",
            "double": "number",
            "null": "null",
        }
        if isinstance(avro_type, str):
            return mapping.get(avro_type, avro_type), False

        if isinstance(avro_type, list):
            # Union type
            is_nullable = "null" in avro_type
            sub_types = [mapping.get(t, str(t)) for t in avro_type if t != "null"]
            if not sub_types:
                return "null", True
            joined = " | ".join(sub_types)
            if is_nullable:
                return f"{joined} | null", True
            return joined, False

        if isinstance(avro_type, dict):
            t = avro_type.get("type")
            if t == "array":
                item_t, _ = cls._avro_type_to_ts(avro_type.get("items", "any"))
                return f"{item_t}[]", False
            elif t == "map":
                val_t, _ = cls._avro_type_to_ts(avro_type.get("values", "any"))
                return f"Record<string, {val_t}>", False
            elif t == "record":
                return avro_type.get("name", "Record"), False
            elif t == "enum":
                symbols = avro_type.get("symbols", [])
                if symbols:
                    return " | ".join(f'"{s}"' for s in symbols), False
                return "string", False

        return "any", False

    @classmethod
    def _avro_type_to_pydantic(
        cls, avro_type: Any, has_default: bool, default_val: Any
    ) -> tuple[str, str | None]:
        mapping = {
            "string": "str",
            "boolean": "bool",
            "bytes": "bytes",
            "int": "int",
            "long": "int",
            "float": "float",
            "double": "float",
            "null": "None",
        }

        if isinstance(avro_type, str):
            py_type = mapping.get(avro_type, avro_type)
            if has_default:
                return py_type, json.dumps(default_val)
            return py_type, None

        if isinstance(avro_type, list):
            # Union
            is_nullable = "null" in avro_type
            sub_types = [mapping.get(t, str(t)) for t in avro_type if t != "null"]
            py_type = " | ".join(sub_types) if sub_types else "None"
            if is_nullable:
                py_type = f"{py_type} | None"
                default_repr = (
                    json.dumps(default_val) if (has_default and default_val is not None) else "None"
                )
                return py_type, default_repr
            return py_type, json.dumps(default_val) if has_default else None

        if isinstance(avro_type, dict):
            t = avro_type.get("type")
            if t == "array":
                item_t, _ = cls._avro_type_to_pydantic(avro_type.get("items", "Any"), False, None)
                return f"list[{item_t}]", "Field(default_factory=list)"
            elif t == "map":
                val_t, _ = cls._avro_type_to_pydantic(avro_type.get("values", "Any"), False, None)
                return f"dict[str, {val_t}]", "Field(default_factory=dict)"
            elif t == "record":
                name = avro_type.get("name", "NestedRecord")
                return name, json.dumps(default_val) if has_default else None

        return "Any", "None" if has_default else None

    # -------------------------------------------------------------------------
    # JSON SCHEMA CODEGEN
    # -------------------------------------------------------------------------
    @classmethod
    def _generate_json_schema(cls, ast: JsonSchemaAST, lang: TargetLanguage) -> str:
        title = cls._clean_identifier(ast.title or "RootModel")
        raw = ast.raw or {}
        defs = raw.get("$defs") or raw.get("definitions") or {}

        if lang == TargetLanguage.TYPESCRIPT:
            lines = [
                "/**",
                " * Generated by ContractHub",
                f" * Title: {title}",
                " */",
                "",
            ]

            # Reusable definitions
            for def_name, def_schema in defs.items():
                if isinstance(def_schema, dict):
                    lines.extend(
                        cls._json_schema_obj_to_ts(cls._clean_identifier(def_name), def_schema)
                    )

            # Main model
            lines.extend(cls._json_schema_obj_to_ts(title, raw))
            return "\n".join(lines).strip() + "\n"

        else:  # PYDANTIC
            lines = [
                "# Generated by ContractHub",
                "from __future__ import annotations",
                "",
                "from typing import Any",
                "from pydantic import BaseModel, Field",
                "",
            ]

            # Reusable definitions
            for def_name, def_schema in defs.items():
                if isinstance(def_schema, dict):
                    lines.extend(
                        cls._json_schema_obj_to_pydantic(
                            cls._clean_identifier(def_name), def_schema
                        )
                    )

            # Main model
            lines.extend(cls._json_schema_obj_to_pydantic(title, raw))
            return "\n".join(lines).strip() + "\n"

    @classmethod
    def _json_schema_obj_to_ts(cls, name: str, schema: dict[str, Any]) -> list[str]:
        lines = [f"export interface {name} {{"]
        props = schema.get("properties", {})
        required = schema.get("required", [])

        if not props:
            lines.append("  [key: string]: any;")
        else:
            for p_name, p_schema in props.items():
                opt = "" if p_name in required else "?"
                ts_type = cls._json_prop_to_ts(p_schema)
                safe_name = f'"{p_name}"' if not p_name.isidentifier() else p_name
                lines.append(f"  {safe_name}{opt}: {ts_type};")

        lines.append("}\n")
        return lines

    @classmethod
    def _json_prop_to_ts(cls, prop: Any) -> str:
        if not isinstance(prop, dict):
            return "any"

        if "$ref" in prop:
            ref = prop["$ref"].split("/")[-1]
            return cls._clean_identifier(ref)

        p_type = prop.get("type")
        if p_type == "string":
            if "enum" in prop:
                return " | ".join(f'"{val}"' for val in prop["enum"])
            return "string"
        elif p_type in ("integer", "number"):
            return "number"
        elif p_type == "boolean":
            return "boolean"
        elif p_type == "array":
            items = prop.get("items", {})
            return f"{cls._json_prop_to_ts(items)}[]"
        elif p_type == "object":
            return "Record<string, any>"
        return "any"

    @classmethod
    def _json_schema_obj_to_pydantic(cls, name: str, schema: dict[str, Any]) -> list[str]:
        lines = [f"class {name}(BaseModel):"]
        props = schema.get("properties", {})
        required = schema.get("required", [])

        if not props:
            lines.append("    pass\n")
            return lines

        for p_name, p_schema in props.items():
            py_type = cls._json_prop_to_pydantic(p_schema)
            is_req = p_name in required
            safe_name = p_name if p_name.isidentifier() else p_name.replace("-", "_")
            alias_part = f', alias="{p_name}"' if safe_name != p_name else ""

            if is_req:
                if alias_part:
                    lines.append(f"    {safe_name}: {py_type} = Field(...{alias_part})")
                else:
                    lines.append(f"    {safe_name}: {py_type}")
            else:
                lines.append(f"    {safe_name}: {py_type} | None = Field(default=None{alias_part})")

        lines.append("")
        return lines

    @classmethod
    def _json_prop_to_pydantic(cls, prop: Any) -> str:
        if not isinstance(prop, dict):
            return "Any"

        if "$ref" in prop:
            ref = prop["$ref"].split("/")[-1]
            return cls._clean_identifier(ref)

        p_type = prop.get("type")
        if p_type == "string":
            return "str"
        elif p_type == "integer":
            return "int"
        elif p_type == "number":
            return "float"
        elif p_type == "boolean":
            return "bool"
        elif p_type == "array":
            items = prop.get("items", {})
            return f"list[{cls._json_prop_to_pydantic(items)}]"
        elif p_type == "object":
            return "dict[str, Any]"
        return "Any"

    # -------------------------------------------------------------------------
    # OPENAPI CODEGEN
    # -------------------------------------------------------------------------
    @classmethod
    def _generate_openapi(cls, ast: OpenApiAST, lang: TargetLanguage) -> str:
        schemas = ast.schemas

        if lang == TargetLanguage.TYPESCRIPT:
            lines = [
                "/**",
                " * Generated by ContractHub",
                f" * API: {ast.title}",
                f" * Version: {ast.version}",
                " */",
                "",
            ]

            if not schemas:
                lines.append("// No component schemas defined.")
                return "\n".join(lines) + "\n"

            for schema_name, schema_def in schemas.items():
                if isinstance(schema_def, dict):
                    clean_name = cls._clean_identifier(schema_name)
                    lines.extend(cls._json_schema_obj_to_ts(clean_name, schema_def))

            return "\n".join(lines).strip() + "\n"

        else:  # PYDANTIC
            lines = [
                "# Generated by ContractHub",
                "from __future__ import annotations",
                "",
                "from typing import Any",
                "from pydantic import BaseModel, Field",
                "",
            ]

            if not schemas:
                lines.append("# No component schemas defined.")
                return "\n".join(lines) + "\n"

            for schema_name, schema_def in schemas.items():
                if isinstance(schema_def, dict):
                    clean_name = cls._clean_identifier(schema_name)
                    lines.extend(cls._json_schema_obj_to_pydantic(clean_name, schema_def))

            return "\n".join(lines).strip() + "\n"

    @classmethod
    def _clean_identifier(cls, name: str) -> str:
        # Convert hyphenated or snake_cased names to PascalCase if needed
        clean = re.sub(r"[^a-zA-Z0-9_]", "_", name)
        if not clean:
            return "Item"
        # If starts with digit, prefix with Model
        if clean[0].isdigit():
            clean = f"Model_{clean}"
        return clean

    # -------------------------------------------------------------------------
    # GRAPHQL CODEGEN
    # -------------------------------------------------------------------------
    @classmethod
    def _generate_graphql(cls, ast: GraphQLAST, lang: TargetLanguage) -> str:
        if lang == TargetLanguage.TYPESCRIPT:
            lines = [
                "/**",
                " * Generated by ContractHub",
                " * Schema: GraphQL SDL",
                " */",
                "",
            ]

            for enum_name, enum_ast in ast.enums.items():
                lines.append(f"export enum {enum_name} {{")
                for val in enum_ast.values:
                    lines.append(f'  {val} = "{val}",')
                lines.append("}\n")

            all_types = {**ast.types, **ast.inputs, **ast.interfaces}
            for type_name, type_ast in all_types.items():
                lines.append(f"export interface {type_name} {{")
                for f_name, f in type_ast.fields.items():
                    ts_t = cls._graphql_type_to_ts(f.type_name)
                    if f.is_list:
                        ts_t = f"{ts_t}[]"
                    opt = "" if f.is_non_null else "?"
                    lines.append(f"  {f_name}{opt}: {ts_t};")
                lines.append("}\n")

            return "\n".join(lines).strip() + "\n"

        else:  # PYDANTIC
            lines = [
                "# Generated by ContractHub",
                "from __future__ import annotations",
                "",
                "from enum import StrEnum",
                "from typing import Any",
                "from pydantic import BaseModel, Field",
                "",
            ]

            for enum_name, enum_ast in ast.enums.items():
                lines.append(f"class {enum_name}(StrEnum):")
                if not enum_ast.values:
                    lines.append("    pass\n")
                else:
                    for val in enum_ast.values:
                        lines.append(f'    {val} = "{val}"')
                    lines.append("")

            all_types = {**ast.types, **ast.inputs, **ast.interfaces}
            for type_name, type_ast in all_types.items():
                lines.append(f"class {type_name}(BaseModel):")
                if not type_ast.fields:
                    lines.append("    pass\n")
                    continue

                for f_name, f in type_ast.fields.items():
                    py_t = cls._graphql_type_to_pydantic(f.type_name)
                    if f.is_list:
                        py_t = f"list[{py_t}]"
                        if not f.is_non_null:
                            lines.append(f"    {f_name}: {py_t} = Field(default_factory=list)")
                        else:
                            lines.append(f"    {f_name}: {py_t}")
                    else:
                        if f.is_non_null:
                            lines.append(f"    {f_name}: {py_t}")
                        else:
                            lines.append(f"    {f_name}: {py_t} | None = None")
                lines.append("")

            return "\n".join(lines).strip() + "\n"

    @classmethod
    def _graphql_type_to_ts(cls, type_name: str) -> str:
        mapping = {
            "String": "string",
            "ID": "string",
            "Int": "number",
            "Float": "number",
            "Boolean": "boolean",
        }
        return mapping.get(type_name, type_name)

    @classmethod
    def _graphql_type_to_pydantic(cls, type_name: str) -> str:
        mapping = {
            "String": "str",
            "ID": "str",
            "Int": "int",
            "Float": "float",
            "Boolean": "bool",
        }
        return mapping.get(type_name, type_name)
